options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: products-dev
steps:
  - name: 'maven:3-eclipse-temurin-21-alpine'
    entrypoint: 'mvn'
    args: [ '-e','-q', 'package' ]
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '.',
            '--no-cache',
            '-t','$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
            '-f','./Docker/gcp/Dockerfile' ]
  - name: gcr.io/cloud-builders/docker
    args: [ 'push', '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA']
  - name: gcr.io/cloud-builders/gcloud
    args: [ 'run', 'deploy', '$_SERVICE_NAME',
            '--image', '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
            '--region', '$_DEPLOY_REGION',
            '--platform', '$_PLATFORM']